filterTrain = {
                  "train_no": "65000K924800",
                  "station_train_code": "K9248",
                  "start_station_telecode": "GGQ",
                  "start_station_name": "广州东",
                  "end_station_telecode": "HYQ",
                  "end_station_name": "衡阳",
                  "from_station_telecode": "GGQ",
                  "from_station_name": "广州东",
                  "to_station_telecode": "HYQ",
                  "to_station_name": "衡阳",
                  "start_time": "01:18",
                  "arrive_time": "07:24",
                  "day_difference": "0",
                  "train_class_name": "",
                  "lishi": "06:06",
                  "canWebBuy": "N",
                  "lishiValue": "366",
                  "yp_info": "10091030001009100000",
                  "control_train_day": "20991231",
                  "start_train_date": "20140127",
                  "seat_feature": "13W3",
                  "yp_ex": "1010",
                  "train_seat_feature": "3",
                  "seat_types": "11",
                  "location_code": "Q7",
                  "from_station_no": "01",
                  "to_station_no": "04",
                  "control_day": 24,
                  "sale_time": "1330",
                  "is_support_card": "0",
                  "gg_num": "--",
                  "gr_num": "--",
                  "qt_num": "--",
                  "rw_num": "--",
                  "rz_num": "--",
                  "tz_num": "--",
                  "wz_num": "无",
                  "yb_num": "--",
                  "yw_num": "--",
                  "yz_num": "无",
                  "ze_num": "--",
                  "zy_num": "--",
                  "swz_num": "--"}
#
#
#
#"start_train_date": "20140127",
#    "station_train_code": "K9248",
#    "start_station_name": "广州东",
#  "start_time": "01:18",
#  "to_station_name": "衡阳",
#    "arrive_time": "07:24",
#"lishi": "06:06",
import  time

s = [ time.strftime('%Y-%m-%d', time.strptime(filterTrain['start_train_date'], '%Y%m%d')),
     filterTrain['station_train_code'] + '次',
     filterTrain['start_station_name'] + '站',
     '(' + filterTrain['start_time'] + '开' + ')',
     '--',
     filterTrain['to_station_name'] + '站',
     '(' + filterTrain['arrive_time'] + '到' + ')',
     filterTrain['lishi']]

print(' '.join(s))